name: Automatic Rebase

on:
  issue_comment:
    types: [created]

jobs:
  rebase:
    if: github.event.issue.pull_request != '' && github.actor == 'prince-chrismc' && contains(github.event.comment.body, '/rebase')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0 # otherwise, you will fail to push refs to dest repo
      - uses: cirrus-actions/rebase@1.4
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_PAT }}
